version: '3'
services:
  db:
    image: mysql:5.6
    container_name: devsmake_db
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: devsmake
      MYSQL_DATABASE: devsmake
      MYSQL_USER: devsmake
      MYSQL_PASSWORD: devsmake
    tty: true
  app:
    build: .
    container_name: devsmake_webapp
    environment:
      DB_HOST: db
      DB_NAME: devsmake
      DB_USER: devsmake
      DB_PASSWORD: devsmake
    restart: on-failure
    ports:
      - "5000:443"
      - "5001:80"
    tty: true
    depends_on:
      - db
    links: 
      - db