// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"devsmake/models"
)

// GetAuthLoginOKCode is the HTTP code returned for type GetAuthLoginOK
const GetAuthLoginOKCode int = 200

/*GetAuthLoginOK login

swagger:response getAuthLoginOK
*/
type GetAuthLoginOK struct {

	/*
	  In: Body
	*/
	Payload *GetAuthLoginOKBody `json:"body,omitempty"`
}

// NewGetAuthLoginOK creates GetAuthLoginOK with default headers values
func NewGetAuthLoginOK() *GetAuthLoginOK {

	return &GetAuthLoginOK{}
}

// WithPayload adds the payload to the get auth login o k response
func (o *GetAuthLoginOK) WithPayload(payload *GetAuthLoginOKBody) *GetAuthLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth login o k response
func (o *GetAuthLoginOK) SetPayload(payload *GetAuthLoginOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAuthLoginDefault error

swagger:response getAuthLoginDefault
*/
type GetAuthLoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthLoginDefault creates GetAuthLoginDefault with default headers values
func NewGetAuthLoginDefault(code int) *GetAuthLoginDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAuthLoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get auth login default response
func (o *GetAuthLoginDefault) WithStatusCode(code int) *GetAuthLoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get auth login default response
func (o *GetAuthLoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get auth login default response
func (o *GetAuthLoginDefault) WithPayload(payload *models.Error) *GetAuthLoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth login default response
func (o *GetAuthLoginDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthLoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
