CREATE TABLE IF NOT EXISTS `posts` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
	`author_id` INT NOT NULL,
	`title` VARCHAR(150) NOT NULL,
	`description` TEXT NOT NULL,
    `deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `modified` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
    UNIQUE KEY (`uuid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `posts_ratings` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`post_uuid` CHAR(36) NOT NULL,
	`rater_id` INT NOT NULL,
    `rating` TINYINT NOT NULL DEFAULT 0,
    `modified` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `posts_comments` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
	`post_uuid` CHAR(36) NOT NULL,
	`author_id` INT NOT NULL,
    `comment` VARCHAR(280) NOT NULL,
    `deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `modified` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
    UNIQUE KEY (`uuid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `posts_submissions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
	`post_uuid` CHAR(36) NOT NULL,
	`author_id` INT NOT NULL,
    `comment` VARCHAR(280) NOT NULL,
    `deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `modified` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
    UNIQUE KEY (`uuid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `posts_submissions_ratings` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`post_submission_uuid` CHAR(36) NOT NULL,
	`rater_id` INT NOT NULL,
    `rating` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `modified` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
