// Code generated by go-swagger; DO NOT EDIT.

// Package restapi DevsMake
//
//  Bringing together users and developers to create amazing projects.
//  Schemes:
//    http
//    https
//  Host: devsmake.com
//  BasePath: /api/v1
//  Version: 1.0.0
//  License: GNU Affero General Public License v3.0 https://www.gnu.org/licenses/agpl-3.0.en.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
