// Code generated by go-swagger; DO NOT EDIT.

// Package restapi DevsMake
//
//  Bringing together users and developers to create amazing projects.
//  Schemes:
//    http
//    https
//  Host: devsmake.com
//  BasePath: /api/v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
