// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Bringing together users and developers to create amazing projects.",
    "title": "DevsMake",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "devsmake.com",
  "basePath": "/api/v1",
  "paths": {
    "/auth/callback": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "return access_token",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/auth/login": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "login through github oauth2",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/healthcheck": {
      "get": {
        "security": [],
        "tags": [
          "general"
        ],
        "summary": "system database health check",
        "responses": {
          "200": {
            "description": "database available",
            "schema": {
              "properties": {
                "status": {
                  "type": "string",
                  "format": "string",
                  "example": "available"
                }
              }
            }
          },
          "500": {
            "description": "database unavailable",
            "schema": {
              "properties": {
                "status": {
                  "type": "string",
                  "format": "string",
                  "example": "unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "tags": [
          "profile"
        ],
        "summary": "profile information and statistics for the current user",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "properties": {
                "identifier": {
                  "type": "integer",
                  "format": "int64"
                },
                "username": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "github_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://github.com/login/oauth/authorize",
      "tokenUrl": "https://github.com/login/oauth/access_token",
      "scopes": {
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "github_auth": [
        "user"
      ]
    }
  ],
  "tags": [
    {
      "description": "General system endpoints",
      "name": "general"
    },
    {
      "description": "Authentication information",
      "name": "auth"
    },
    {
      "description": "Profile information",
      "name": "profile"
    }
  ],
  "externalDocs": {
    "description": "Find out more about DevsMake",
    "url": "https://devsmake.com"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Bringing together users and developers to create amazing projects.",
    "title": "DevsMake",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "devsmake.com",
  "basePath": "/api/v1",
  "paths": {
    "/auth/callback": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "return access_token",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/auth/login": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "login through github oauth2",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/healthcheck": {
      "get": {
        "security": [],
        "tags": [
          "general"
        ],
        "summary": "system database health check",
        "responses": {
          "200": {
            "description": "database available",
            "schema": {
              "properties": {
                "status": {
                  "type": "string",
                  "format": "string",
                  "example": "available"
                }
              }
            }
          },
          "500": {
            "description": "database unavailable",
            "schema": {
              "properties": {
                "status": {
                  "type": "string",
                  "format": "string",
                  "example": "unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "tags": [
          "profile"
        ],
        "summary": "profile information and statistics for the current user",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "properties": {
                "identifier": {
                  "type": "integer",
                  "format": "int64"
                },
                "username": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "github_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://github.com/login/oauth/authorize",
      "tokenUrl": "https://github.com/login/oauth/access_token",
      "scopes": {
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "github_auth": [
        "user"
      ]
    }
  ],
  "tags": [
    {
      "description": "General system endpoints",
      "name": "general"
    },
    {
      "description": "Authentication information",
      "name": "auth"
    },
    {
      "description": "Profile information",
      "name": "profile"
    }
  ],
  "externalDocs": {
    "description": "Find out more about DevsMake",
    "url": "https://devsmake.com"
  }
}`))
}
