// Code generated by go-swagger; DO NOT EDIT.

package idea_submissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"devsmake/models"
)

// GetIdeasUUIDSubmissionsHandlerFunc turns a function with the right signature into a get ideas UUID submissions handler
type GetIdeasUUIDSubmissionsHandlerFunc func(GetIdeasUUIDSubmissionsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIdeasUUIDSubmissionsHandlerFunc) Handle(params GetIdeasUUIDSubmissionsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetIdeasUUIDSubmissionsHandler interface for that can handle valid get ideas UUID submissions params
type GetIdeasUUIDSubmissionsHandler interface {
	Handle(GetIdeasUUIDSubmissionsParams, *models.Principal) middleware.Responder
}

// NewGetIdeasUUIDSubmissions creates a new http.Handler for the get ideas UUID submissions operation
func NewGetIdeasUUIDSubmissions(ctx *middleware.Context, handler GetIdeasUUIDSubmissionsHandler) *GetIdeasUUIDSubmissions {
	return &GetIdeasUUIDSubmissions{Context: ctx, Handler: handler}
}

/* GetIdeasUUIDSubmissions swagger:route GET /ideas/{uuid}/submissions idea submissions getIdeasUuidSubmissions

gets all submissions for a idea post

*/
type GetIdeasUUIDSubmissions struct {
	Context *middleware.Context
	Handler GetIdeasUUIDSubmissionsHandler
}

func (o *GetIdeasUUIDSubmissions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetIdeasUUIDSubmissionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
