// Code generated by go-swagger; DO NOT EDIT.

package idea_submissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"devsmake/models"
)

// PostIdeasUUIDSubmissionsHandlerFunc turns a function with the right signature into a post ideas UUID submissions handler
type PostIdeasUUIDSubmissionsHandlerFunc func(PostIdeasUUIDSubmissionsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostIdeasUUIDSubmissionsHandlerFunc) Handle(params PostIdeasUUIDSubmissionsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostIdeasUUIDSubmissionsHandler interface for that can handle valid post ideas UUID submissions params
type PostIdeasUUIDSubmissionsHandler interface {
	Handle(PostIdeasUUIDSubmissionsParams, *models.Principal) middleware.Responder
}

// NewPostIdeasUUIDSubmissions creates a new http.Handler for the post ideas UUID submissions operation
func NewPostIdeasUUIDSubmissions(ctx *middleware.Context, handler PostIdeasUUIDSubmissionsHandler) *PostIdeasUUIDSubmissions {
	return &PostIdeasUUIDSubmissions{Context: ctx, Handler: handler}
}

/* PostIdeasUUIDSubmissions swagger:route POST /ideas/{uuid}/submissions idea submissions postIdeasUuidSubmissions

creates a submission for the idea post

*/
type PostIdeasUUIDSubmissions struct {
	Context *middleware.Context
	Handler PostIdeasUUIDSubmissionsHandler
}

func (o *PostIdeasUUIDSubmissions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostIdeasUUIDSubmissionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
