// Code generated by go-swagger; DO NOT EDIT.

package idea_submissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"devsmake/models"
)

// PostIdeasUUIDSubmissionsOKCode is the HTTP code returned for type PostIdeasUUIDSubmissionsOK
const PostIdeasUUIDSubmissionsOKCode int = 200

/*PostIdeasUUIDSubmissionsOK the submission post which was created

swagger:response postIdeasUuidSubmissionsOK
*/
type PostIdeasUUIDSubmissionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Submission `json:"body,omitempty"`
}

// NewPostIdeasUUIDSubmissionsOK creates PostIdeasUUIDSubmissionsOK with default headers values
func NewPostIdeasUUIDSubmissionsOK() *PostIdeasUUIDSubmissionsOK {

	return &PostIdeasUUIDSubmissionsOK{}
}

// WithPayload adds the payload to the post ideas Uuid submissions o k response
func (o *PostIdeasUUIDSubmissionsOK) WithPayload(payload *models.Submission) *PostIdeasUUIDSubmissionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post ideas Uuid submissions o k response
func (o *PostIdeasUUIDSubmissionsOK) SetPayload(payload *models.Submission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIdeasUUIDSubmissionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostIdeasUUIDSubmissionsDefault error

swagger:response postIdeasUuidSubmissionsDefault
*/
type PostIdeasUUIDSubmissionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostIdeasUUIDSubmissionsDefault creates PostIdeasUUIDSubmissionsDefault with default headers values
func NewPostIdeasUUIDSubmissionsDefault(code int) *PostIdeasUUIDSubmissionsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostIdeasUUIDSubmissionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post ideas UUID submissions default response
func (o *PostIdeasUUIDSubmissionsDefault) WithStatusCode(code int) *PostIdeasUUIDSubmissionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post ideas UUID submissions default response
func (o *PostIdeasUUIDSubmissionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post ideas UUID submissions default response
func (o *PostIdeasUUIDSubmissionsDefault) WithPayload(payload *models.Error) *PostIdeasUUIDSubmissionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post ideas UUID submissions default response
func (o *PostIdeasUUIDSubmissionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIdeasUUIDSubmissionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
