// Code generated by go-swagger; DO NOT EDIT.

package idea_submissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"devsmake/models"
)

// PutIdeasUUIDSubmissionsRateOKCode is the HTTP code returned for type PutIdeasUUIDSubmissionsRateOK
const PutIdeasUUIDSubmissionsRateOKCode int = 200

/*PutIdeasUUIDSubmissionsRateOK the subbmision post which was rated

swagger:response putIdeasUuidSubmissionsRateOK
*/
type PutIdeasUUIDSubmissionsRateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Submission `json:"body,omitempty"`
}

// NewPutIdeasUUIDSubmissionsRateOK creates PutIdeasUUIDSubmissionsRateOK with default headers values
func NewPutIdeasUUIDSubmissionsRateOK() *PutIdeasUUIDSubmissionsRateOK {

	return &PutIdeasUUIDSubmissionsRateOK{}
}

// WithPayload adds the payload to the put ideas Uuid submissions rate o k response
func (o *PutIdeasUUIDSubmissionsRateOK) WithPayload(payload *models.Submission) *PutIdeasUUIDSubmissionsRateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put ideas Uuid submissions rate o k response
func (o *PutIdeasUUIDSubmissionsRateOK) SetPayload(payload *models.Submission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIdeasUUIDSubmissionsRateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutIdeasUUIDSubmissionsRateDefault error

swagger:response putIdeasUuidSubmissionsRateDefault
*/
type PutIdeasUUIDSubmissionsRateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutIdeasUUIDSubmissionsRateDefault creates PutIdeasUUIDSubmissionsRateDefault with default headers values
func NewPutIdeasUUIDSubmissionsRateDefault(code int) *PutIdeasUUIDSubmissionsRateDefault {
	if code <= 0 {
		code = 500
	}

	return &PutIdeasUUIDSubmissionsRateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put ideas UUID submissions rate default response
func (o *PutIdeasUUIDSubmissionsRateDefault) WithStatusCode(code int) *PutIdeasUUIDSubmissionsRateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put ideas UUID submissions rate default response
func (o *PutIdeasUUIDSubmissionsRateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put ideas UUID submissions rate default response
func (o *PutIdeasUUIDSubmissionsRateDefault) WithPayload(payload *models.Error) *PutIdeasUUIDSubmissionsRateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put ideas UUID submissions rate default response
func (o *PutIdeasUUIDSubmissionsRateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIdeasUUIDSubmissionsRateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
