// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthcheckOKCode is the HTTP code returned for type GetHealthcheckOK
const GetHealthcheckOKCode int = 200

/*GetHealthcheckOK database available

swagger:response getHealthcheckOK
*/
type GetHealthcheckOK struct {

	/*
	  In: Body
	*/
	Payload *GetHealthcheckOKBody `json:"body,omitempty"`
}

// NewGetHealthcheckOK creates GetHealthcheckOK with default headers values
func NewGetHealthcheckOK() *GetHealthcheckOK {

	return &GetHealthcheckOK{}
}

// WithPayload adds the payload to the get healthcheck o k response
func (o *GetHealthcheckOK) WithPayload(payload *GetHealthcheckOKBody) *GetHealthcheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthcheck o k response
func (o *GetHealthcheckOK) SetPayload(payload *GetHealthcheckOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthcheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHealthcheckInternalServerErrorCode is the HTTP code returned for type GetHealthcheckInternalServerError
const GetHealthcheckInternalServerErrorCode int = 500

/*GetHealthcheckInternalServerError database unavailable

swagger:response getHealthcheckInternalServerError
*/
type GetHealthcheckInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *GetHealthcheckInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetHealthcheckInternalServerError creates GetHealthcheckInternalServerError with default headers values
func NewGetHealthcheckInternalServerError() *GetHealthcheckInternalServerError {

	return &GetHealthcheckInternalServerError{}
}

// WithPayload adds the payload to the get healthcheck internal server error response
func (o *GetHealthcheckInternalServerError) WithPayload(payload *GetHealthcheckInternalServerErrorBody) *GetHealthcheckInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthcheck internal server error response
func (o *GetHealthcheckInternalServerError) SetPayload(payload *GetHealthcheckInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthcheckInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
