swagger: "2.0"
info:
  description: "Bringing together users and developers to create amazing projects."
  version: "1.0.0"
  title: "DevsMake"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "devsmake.com"
basePath: "/api/v1"
tags:
- name: "api"
  description: "Everything about the api"
schemes:
- "https"
paths:
  /:
    get:
      tags:
      - "api"
      summary: "Information pertaining to the api"
      description: "Information such as current version and status of the system"
      operationId: "getApiInfo"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - github_auth: []
securityDefinitions:
  github_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about DevsMake"
  url: "http://devsmake.com"