// Code generated by go-swagger; DO NOT EDIT.

package idea_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"devsmake/models"
)

// GetIdeasOKCode is the HTTP code returned for type GetIdeasOK
const GetIdeasOKCode int = 200

/*GetIdeasOK ideas array

swagger:response getIdeasOK
*/
type GetIdeasOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Idea `json:"body,omitempty"`
}

// NewGetIdeasOK creates GetIdeasOK with default headers values
func NewGetIdeasOK() *GetIdeasOK {

	return &GetIdeasOK{}
}

// WithPayload adds the payload to the get ideas o k response
func (o *GetIdeasOK) WithPayload(payload []*models.Idea) *GetIdeasOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ideas o k response
func (o *GetIdeasOK) SetPayload(payload []*models.Idea) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIdeasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Idea, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetIdeasDefault error

swagger:response getIdeasDefault
*/
type GetIdeasDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetIdeasDefault creates GetIdeasDefault with default headers values
func NewGetIdeasDefault(code int) *GetIdeasDefault {
	if code <= 0 {
		code = 500
	}

	return &GetIdeasDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get ideas default response
func (o *GetIdeasDefault) WithStatusCode(code int) *GetIdeasDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get ideas default response
func (o *GetIdeasDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get ideas default response
func (o *GetIdeasDefault) WithPayload(payload *models.Error) *GetIdeasDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ideas default response
func (o *GetIdeasDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIdeasDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
