// Code generated by go-swagger; DO NOT EDIT.

package idea_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetIdeasUUIDHandlerFunc turns a function with the right signature into a get ideas UUID handler
type GetIdeasUUIDHandlerFunc func(GetIdeasUUIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIdeasUUIDHandlerFunc) Handle(params GetIdeasUUIDParams) middleware.Responder {
	return fn(params)
}

// GetIdeasUUIDHandler interface for that can handle valid get ideas UUID params
type GetIdeasUUIDHandler interface {
	Handle(GetIdeasUUIDParams) middleware.Responder
}

// NewGetIdeasUUID creates a new http.Handler for the get ideas UUID operation
func NewGetIdeasUUID(ctx *middleware.Context, handler GetIdeasUUIDHandler) *GetIdeasUUID {
	return &GetIdeasUUID{Context: ctx, Handler: handler}
}

/* GetIdeasUUID swagger:route GET /ideas/{uuid} idea post getIdeasUuid

gets an idea by uuid

*/
type GetIdeasUUID struct {
	Context *middleware.Context
	Handler GetIdeasUUIDHandler
}

func (o *GetIdeasUUID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetIdeasUUIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
