// Code generated by go-swagger; DO NOT EDIT.

package idea_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"devsmake/models"
)

// PostIdeaHandlerFunc turns a function with the right signature into a post idea handler
type PostIdeaHandlerFunc func(PostIdeaParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostIdeaHandlerFunc) Handle(params PostIdeaParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostIdeaHandler interface for that can handle valid post idea params
type PostIdeaHandler interface {
	Handle(PostIdeaParams, *models.Principal) middleware.Responder
}

// NewPostIdea creates a new http.Handler for the post idea operation
func NewPostIdea(ctx *middleware.Context, handler PostIdeaHandler) *PostIdea {
	return &PostIdea{Context: ctx, Handler: handler}
}

/* PostIdea swagger:route POST /idea idea post postIdea

create an idea post

*/
type PostIdea struct {
	Context *middleware.Context
	Handler PostIdeaHandler
}

func (o *PostIdea) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostIdeaParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
