// Code generated by go-swagger; DO NOT EDIT.

package idea_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"devsmake/models"
)

// PostIdeasHandlerFunc turns a function with the right signature into a post ideas handler
type PostIdeasHandlerFunc func(PostIdeasParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostIdeasHandlerFunc) Handle(params PostIdeasParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostIdeasHandler interface for that can handle valid post ideas params
type PostIdeasHandler interface {
	Handle(PostIdeasParams, *models.Principal) middleware.Responder
}

// NewPostIdeas creates a new http.Handler for the post ideas operation
func NewPostIdeas(ctx *middleware.Context, handler PostIdeasHandler) *PostIdeas {
	return &PostIdeas{Context: ctx, Handler: handler}
}

/* PostIdeas swagger:route POST /ideas idea post postIdeas

create an idea post

*/
type PostIdeas struct {
	Context *middleware.Context
	Handler PostIdeasHandler
}

func (o *PostIdeas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostIdeasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
