// Code generated by go-swagger; DO NOT EDIT.

package idea_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"devsmake/models"
)

// PutIdeasUUIDRateOKCode is the HTTP code returned for type PutIdeasUUIDRateOK
const PutIdeasUUIDRateOKCode int = 200

/*PutIdeasUUIDRateOK the idea post which was rated

swagger:response putIdeasUuidRateOK
*/
type PutIdeasUUIDRateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Idea `json:"body,omitempty"`
}

// NewPutIdeasUUIDRateOK creates PutIdeasUUIDRateOK with default headers values
func NewPutIdeasUUIDRateOK() *PutIdeasUUIDRateOK {

	return &PutIdeasUUIDRateOK{}
}

// WithPayload adds the payload to the put ideas Uuid rate o k response
func (o *PutIdeasUUIDRateOK) WithPayload(payload *models.Idea) *PutIdeasUUIDRateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put ideas Uuid rate o k response
func (o *PutIdeasUUIDRateOK) SetPayload(payload *models.Idea) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIdeasUUIDRateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutIdeasUUIDRateDefault error

swagger:response putIdeasUuidRateDefault
*/
type PutIdeasUUIDRateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutIdeasUUIDRateDefault creates PutIdeasUUIDRateDefault with default headers values
func NewPutIdeasUUIDRateDefault(code int) *PutIdeasUUIDRateDefault {
	if code <= 0 {
		code = 500
	}

	return &PutIdeasUUIDRateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put ideas UUID rate default response
func (o *PutIdeasUUIDRateDefault) WithStatusCode(code int) *PutIdeasUUIDRateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put ideas UUID rate default response
func (o *PutIdeasUUIDRateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put ideas UUID rate default response
func (o *PutIdeasUUIDRateDefault) WithPayload(payload *models.Error) *PutIdeasUUIDRateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put ideas UUID rate default response
func (o *PutIdeasUUIDRateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIdeasUUIDRateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
