// Code generated by go-swagger; DO NOT EDIT.

package idea_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"devsmake/models"
)

// PutIdeaUUIDRateHandlerFunc turns a function with the right signature into a put idea UUID rate handler
type PutIdeaUUIDRateHandlerFunc func(PutIdeaUUIDRateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutIdeaUUIDRateHandlerFunc) Handle(params PutIdeaUUIDRateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutIdeaUUIDRateHandler interface for that can handle valid put idea UUID rate params
type PutIdeaUUIDRateHandler interface {
	Handle(PutIdeaUUIDRateParams, *models.Principal) middleware.Responder
}

// NewPutIdeaUUIDRate creates a new http.Handler for the put idea UUID rate operation
func NewPutIdeaUUIDRate(ctx *middleware.Context, handler PutIdeaUUIDRateHandler) *PutIdeaUUIDRate {
	return &PutIdeaUUIDRate{Context: ctx, Handler: handler}
}

/* PutIdeaUUIDRate swagger:route PUT /idea/{uuid}/rate idea post putIdeaUuidRate

rate an idea post

*/
type PutIdeaUUIDRate struct {
	Context *middleware.Context
	Handler PutIdeaUUIDRateHandler
}

func (o *PutIdeaUUIDRate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutIdeaUUIDRateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutIdeaUUIDRateBody put idea UUID rate body
//
// swagger:model PutIdeaUUIDRateBody
type PutIdeaUUIDRateBody struct {

	// rating
	// Example: 10
	// Required: true
	Rating *int64 `json:"rating"`
}

// Validate validates this put idea UUID rate body
func (o *PutIdeaUUIDRateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRating(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutIdeaUUIDRateBody) validateRating(formats strfmt.Registry) error {

	if err := validate.Required("rating"+"."+"rating", "body", o.Rating); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this put idea UUID rate body based on context it is used
func (o *PutIdeaUUIDRateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutIdeaUUIDRateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutIdeaUUIDRateBody) UnmarshalBinary(b []byte) error {
	var res PutIdeaUUIDRateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
