// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProfileIDHandlerFunc turns a function with the right signature into a get profile ID handler
type GetProfileIDHandlerFunc func(GetProfileIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProfileIDHandlerFunc) Handle(params GetProfileIDParams) middleware.Responder {
	return fn(params)
}

// GetProfileIDHandler interface for that can handle valid get profile ID params
type GetProfileIDHandler interface {
	Handle(GetProfileIDParams) middleware.Responder
}

// NewGetProfileID creates a new http.Handler for the get profile ID operation
func NewGetProfileID(ctx *middleware.Context, handler GetProfileIDHandler) *GetProfileID {
	return &GetProfileID{Context: ctx, Handler: handler}
}

/* GetProfileID swagger:route GET /profile/{id} profile getProfileId

profile information and statistics for the specified user id

*/
type GetProfileID struct {
	Context *middleware.Context
	Handler GetProfileIDHandler
}

func (o *GetProfileID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProfileIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
