// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"devsmake/models"
)

// GetProfileHandlerFunc turns a function with the right signature into a get profile handler
type GetProfileHandlerFunc func(GetProfileParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProfileHandlerFunc) Handle(params GetProfileParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetProfileHandler interface for that can handle valid get profile params
type GetProfileHandler interface {
	Handle(GetProfileParams, *models.Principal) middleware.Responder
}

// NewGetProfile creates a new http.Handler for the get profile operation
func NewGetProfile(ctx *middleware.Context, handler GetProfileHandler) *GetProfile {
	return &GetProfile{Context: ctx, Handler: handler}
}

/* GetProfile swagger:route GET /profile profile getProfile

profile information and statistics for the current user

*/
type GetProfile struct {
	Context *middleware.Context
	Handler GetProfileHandler
}

func (o *GetProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProfileParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetProfileOKBody get profile o k body
//
// swagger:model GetProfileOKBody
type GetProfileOKBody struct {

	// identifier
	Identifier int64 `json:"identifier,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this get profile o k body
func (o *GetProfileOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get profile o k body based on context it is used
func (o *GetProfileOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetProfileOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProfileOKBody) UnmarshalBinary(b []byte) error {
	var res GetProfileOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
