// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Profile profile
//
// swagger:model Profile
type Profile struct {

	// avatar url
	AvatarURL string `json:"avatar_url,omitempty"`

	// identifier
	Identifier int64 `json:"identifier,omitempty"`

	// points
	Points int64 `json:"points,omitempty"`

	// total comments
	TotalComments int64 `json:"total_comments,omitempty"`

	// total posts
	TotalPosts int64 `json:"total_posts,omitempty"`

	// total ratings
	TotalRatings int64 `json:"total_ratings,omitempty"`

	// total submissions
	TotalSubmissions int64 `json:"total_submissions,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this profile
func (m *Profile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this profile based on context it is used
func (m *Profile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Profile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Profile) UnmarshalBinary(b []byte) error {
	var res Profile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
